# Generated by Django 3.1 on 2020-08-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_attachments_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachments',
            new_name='Attachment',
        ),
    ]
