# Generated by Django 3.1 on 2020-08-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200826_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='email',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
